Feature: OAuth 2.0를 사용한 로그인 구현 및  에러 토스트 작성
Figci/Figci-Client pull request #23
Opened 2024-02-04 15:35 UTC by kyeongjun-ko

## Fix (이슈 번호)
closes #2 

<br />

## 해결 하려던 문제를 알려주세요

#### 온보딩 페이지에서 로그인 버튼 클릭시 피그마 사용자 인증 페이지 리다이렉트 후 
 토큰 요청 로직 실행후 클라이언트의 Local Storage 에 저장한다.

#### 로직 순서
1. 로그인 요청시 피그마 사용자 인증 페이지로 리다이렉트 한다.
2. 인증 페이지에서 권한 승인 후 인증 코드를 콜백 페이지(/new)에 전달한다.
3. URI에 전달된 쿼리스트링으로  인증 코드와 state를 받은 후 state를 검증한다.
4. 검증 후 인증 코드로 토큰 요청후 응답은 JSON 형태로 localstorage 에 저장한다.
5. 피그마 API를 요청시 로컬 스토리지에 토큰을 헤더에 담아 요청한다.

<br />

## 어떻게 해결했나요?

### 1. ESLint의  jsx-ally  > `label-has-associated-control` 규칙에러

> `jsx-a11y/label-has-associated-control`은 jsx 요소의 접근성을 강화하기 위한 ESLint 규칙으로 form label이 form control과 관련이 있는지 즉, label이 어떤 form input을 가르키고 있는지 확인한다! 

![스크린샷1](https://github.com/Figci/Figci-Client/assets/95596243/df2883cb-a33a-4

```
// 방법 1. `<label>`의 for 또는 htmlFor 과 `<Input>` id 를 연결한다.
<label htmlFor="username-input">Username</label>
<input id="username-input" name="login-username" type="text" />
// 방법 2. label 이 설명하는 태그를 감싸버린다.
<label>Username
<input name="login-username" type="text" />
</label>
```

### 2. 의존성 패키지 설치시 `npm install` 에러 => 유저의 파일 권한 설정
패키지 설치 에러로 sudo 명령어로 설치했는데 이런 경우 node modules의 파일은 접근 권한을 사용자 이름이 아닌 root로 설정 한다. 그래서 mac 사용자가  `npm run dev`을 사용 할 수 없다.
![스크린샷2](https://github.com/Figci/Figci-Client/assets/95596243/925088d9-0fd4-4bc1-ab05-7ee70178439f)

- 현재 프로젝트 파일 접근 권한 사용자를 확인한다.
- 현재 나의 컴퓨터 유저 명을 확인한다.
- 프로젝트 파일의 유저 권한을 root => 사용자 이름으로 변경한다.
- npm install, npm run dev 정상 실행 확인 한다.

### 3. git push origin <브랜치 명> 에러 발생 => 깃 토큰 만료시 리프레쉬
![스크린샷3](https://github.com/Figci/Figci-Client/assets/95596243/5520ed9b-fc0b-42b5-88de-d646e13ca1c4)
490-980e-415dff718bf9)

<br />

## 전달 사항이 있나요?

#### 1. API 호출시 BASE_URI 과 REDIRECT_URI 을 환경 변수로 설정했음
```
    // .env
    VITE_FIGMA_BASE_API_URL=https://www.figma.com
    VITE_FIGMA_REDIRECT_URL=http://localhost:5173/new
    
    // auth.js
    const baseURI = import.meta.env.VITE_FIGMA_BASE_API_URL;
    const redirectURI = import.meta.env.VITE_FIGMA_REDIRECT_URL;
```

#### 2. 에러토스트에 전달할 상태 코드와, 메세지를 어떤 형식으로 표시할것인가?
Ex) `상태 코드 : ${status} , 메세지 : ${message}`

<br />
## 잠깐! 확인해보셨나요?
- [x]  셀프 리뷰는 완료하셨나요?
- [x]  가장 최신 브랜치를 pull했나요?
- [x]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [x]  코드 컨벤션을 모두 지켰나요?
- [x]  적절한 라벨이 있나요?
- [x]  assignee가 있나요?
<br />

2024-02-04 16:19 UTC, doitchuu requested changes
P1 반영 내용이 있어 먼저 코멘트 남기고, 추가로 기입하겠습니다!

2024-02-04 16:19 UTC, doitchuu commented on src/components/NewProject/index.jsx
>  function NewProejct() {
P1: 컴포넌트명에 오타가 있었네요. 해당 오타 수정 부탁 드립니다.

```suggestion
function NewProject() {
```

2024-02-04 16:19 UTC, doitchuu commented on src/components/NewProject/index.jsx
> +        console.log("accessToken", JSON.stringify(accessToken));
P1: console.log 삭제 부탁드립니다.
```suggestion
```

2024-02-04 17:31 UTC, tjd985 requested changes
코멘트 확인 부탁드립니다!

2024-02-04 17:31 UTC, tjd985 commented on src/services/auth.js
> +const redirectURI = import.meta.env.VITE_FIGMA_REDIRECT_URL;
- `P1`
상수명은 `URL`로 되어져있는데 변수는 `URI`로 받고있습니다!
통일시켜 주세요!

2024-02-04 17:31 UTC, tjd985 commented on src/components/utils/generateURI.js
> +    });
- `P1`
해당 구문은
```suggestion
    for (const key in queryParams) {
      if (queryParams.hasOwnProperty(key)) {
        apiUri.searchParams.append(key, queryParams[key]);
      }
    }
```

이렇게 `iteration`을 줄일 수 있지 않을까요?

2024-02-04 17:31 UTC, tjd985 commented on src/components/shared/Toast.jsx
> +  }
```suggestion
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  
  to {
    opacity: 1;
    transform: translateY(0);
  }
```
- `P1`
개행 부탁드립니다!

2024-02-04 17:31 UTC, tjd985 commented on src/components/shared/Toast.jsx
> +  text-align: center;
제가 공유한 CSS-writing-convention을 기반으로 작성해주셨군요!
피드백이 빠르게 반영되니 좋네요 👍🏻

- `P3`
다만, `color-code`에서 문자열이 반복 될 시 3글자로 줄일 수 있습니다!
(#000000 → #000)
저는 앞에서 이러한 경우엔 3개로 줄여놨는데, 혹시 어떤게 더 나은것 같은지 궁금합니다!

(한가지 표기법으로 통일이 되었으면 합니다!)

2024-02-04 17:31 UTC, tjd985 commented on src/components/shared/Toast.jsx
> +    </Toast>
공통 `toast`컴포넌트를 만들어 주셨네요!
경준님 덕분에 코드 재사용성이 크게 늘어날 것 같습니다!

2024-02-04 17:31 UTC, tjd985 commented on src/components/shared/Toast.jsx
> +  }, [setToast]);
사이드 이펙트 잊지않고 처리해 주셨군요!

2024-02-04 17:31 UTC, tjd985 commented on src/components/Onboarding/index.jsx
> +    }
- `P2`
```suggestion
    if (isClicked) {
      getAuth();
      
      setIsClicked(false);
    }
```

이후 사이드 이펙트를 방지하기 위해 `getAuth()` 호출 후 다시 `isClicked`를 `false`로 설정해주시는 것은 어떨까요!

2024-02-04 17:31 UTC, tjd985 commented on src/components/NewProject/index.jsx
> +    if (state === "randomstring") {
- `P1`
`state`의 값이 "randomstring"이라는 것을 노출시키기 보다는
`.env`를 통해서 상수처리 해주시는것이 안전해 보입니다!

2024-02-04 17:45 UTC, tjd985 commented on src/components/NewProject/index.jsx
> +        console.error("Error fetching token:", error);
`console.err`를 통해서 에러를 출력하기보다는
유저를 `Onboarding`컴포넌트로 `redirect` 시키고, `toast`를 이용해서 로그인에 실패했다는 메세지를 띄워 주는것이
더욱 유저 친화적일 것 같습니다!

2024-02-05 01:27 UTC, kyeongjun-ko commented on package.json
> +    "axios": "^1.6.7",
피그마 API 요청시 axios로 테스트 했었는데
확인하지 못하고 올리게 됬습니다. 수정하겠습니다.

2024-02-05 01:29 UTC, kyeongjun-ko commented on src/components/App.jsx
> +import ProjectVersion from "./ProjectVersion";
VSCode `Auto Import`  익스텐션 사용으로 자동 정렬 되었는데, 
익스텐션 미사용하고 저희 페이지 라우터 순으로 수정하겠습니다.

2024-02-05 01:29 UTC, kyeongjun-ko commented on src/components/NewProject/index.jsx
>  function NewProejct() {
PR시 오타 확인하겠습니다.

2024-02-05 01:30 UTC, kyeongjun-ko commented on src/components/NewProject/index.jsx
> +        console.log("accessToken", JSON.stringify(accessToken));
네 확인했습니다.

2024-02-05 01:30 UTC, kyeongjun-ko commented on src/components/NewProject/index.jsx
> +        console.error("Error fetching token:", error);
온보딩 페이지에서 만든 에러토스트를 띄울수있게 추가하겠습니다.

2024-02-05 01:41 UTC, kyeongjun-ko commented on src/components/shared/Toast.jsx
> +  text-align: center;
지난번 성호님 온보딩 페이지 작성시 슬기님께서 리뷰 달아주셨는데
명시적이기도 하고 다른 색상코드와 동일하게 쓸수있는 6글자로 쓰는게 좋다고 생각합니다.
같은 색깔일때도 6글자를 사용하자 어떠신가요? @doitchuu @tjd985

2024-02-05 01:45 UTC, doitchuu reviewed
리뷰 부족했던 부분도 더 달았습니다. 확인해주시면 감사하겠습니다!

2024-02-05 01:45 UTC, doitchuu commented on src/components/Onboarding/index.jsx
> +import { getAuth } from "../../services/auth";
P1: 해당 import 문도 기준이 정해지면 같이 반영 부탁드립니다 👍

2024-02-05 01:45 UTC, doitchuu commented on src/components/Onboarding/index.jsx
> +        <Button handleClick={onClickButtonHandler} size="lg">
P4: 해당 버튼을 클릭하면 로그인을 할 수 있는 화면으로 넘어간다는 의미에서 Login이 들어가는 게 어떨까요? 

```suggestion
        <Button onClick={handleLogin} size="lg">
```

2024-02-05 01:45 UTC, doitchuu commented on src/components/shared/Toast.jsx
> +import { useEffect } from "react";
해당 부분도 같이 순서 반영 부탁드립니다.

2024-02-05 01:45 UTC, doitchuu commented on src/components/shared/Toast.jsx
> +    }, 3000);
P3: `3000`이라는 숫자는 상수 처리하는 건 어떨까요?

2024-02-05 01:45 UTC, doitchuu commented on src/components/shared/Toast.jsx
> +        <p>{`status code: ${status} messags: ${message}`}</p>
status코드와 메세지를 따로 처리해주신 점이 좋은 것 같습니다 👍

2024-02-05 01:48 UTC, kyeongjun-ko commented on src/components/utils/generateURI.js
> +    });
`Object.keys`는 O(n) 인 반면에 `hasOwnProperty()`는 O(1)의 시간 복잡도를 갖고있네요
2n -> n 으로 시간복잡도를 줄일수 있어 좋겠군요 바로 반영하겠습니다.

2024-02-05 01:50 UTC, kyeongjun-ko commented on src/services/auth.js
> +const redirectURI = import.meta.env.VITE_FIGMA_REDIRECT_URL;
네 모두 URI 로 반영하겠습니다. 코멘트 감사합니다.

2024-02-05 02:45 UTC, kyeongjun-ko commented on src/components/shared/Toast.jsx
> +    }, 3000);
네 좋습니다.

2024-02-05 03:10 UTC, kyeongjun-ko commented on src/components/NewProject/index.jsx
> +    if (state === "randomstring") {
.env  ㅍㅏㅇㅣㄹ

2024-02-05 03:10 UTC, kyeongjun-ko commented on src/components/Onboarding/index.jsx
> +        <Button handleClick={onClickButtonHandler} size="lg">
버튼 컴포넌트를 재사용 하기 위해서 버튼 컴포넌트의 속성을 사용했습니다.

2024-02-05 06:11 UTC, tjd985 requested changes
코멘트 남겼습니다!

2024-02-05 06:11 UTC, tjd985 commented on src/components/App.jsx
> +import NewProject from "./NewProject";
```suggestion
// import 외부 라이브러리 (react와 관련된 라이브러리부터 ~ 스타일 라이브러리 순으로)

// import 컴포넌트

// import 유틸함수
```
저는 이렇게 3묶음으로 import를 작성하는 편인데 혹시 어떠신가요?

2024-02-05 06:11 UTC, tjd985 commented on src/components/NewProject/index.jsx
> +function NewProject() {
오탈자 수정 반영이 안됬습니다!

2024-02-05 06:11 UTC, tjd985 commented on src/components/utils/generateURI.js
> +    });
수정 반영이 안됬습니다!

2024-02-05 06:32 UTC, tjd985 approved these changes
확인했습니다!
수정사항 반영하시느라 고생하셨습니다.

2024-02-05 06:34 UTC, doitchuu approved these changes
코드 리뷰 반영하시느라 고생하셨습니다 👍

2024-02-05 06:34 UTC, doitchuu commented on src/components/App.jsx
> +import NewProject from "./NewProject";
해당 방식으로 통일하겠습니다.

2024-02-05 06:34 UTC, doitchuu commented on src/components/constants/timeConstants.js
> +export default DELAY_TIME;
후에 상수가 나오면 상수 간 데이터를 묶어줘도 좋을 것 같습니다 :)

2024-02-05 06:53 UTC, merged