Feat: 페이지 별 입력 값 zustand 상태 업데이트 로직 및 공통 컴포넌트 적용
Figci/Figci-Client pull request #28
Opened 2024-02-07 15:13 UTC by kyeongjun-ko

## Fix (이슈 번호)

closes #5, #6, #27 

<br />

## 해결하려던 문제를 알려주세요!

- **1.** 페이지를 이동하며 사용자의 입력값을 저장해서 데이터를 요청하기 위한 zustand 상태 업데이트 로직 
  - URI 페이지 에서 사용자가 입력한 피그마 프로젝트 URI 에서 파일키  zustand 상태 업데이트
  - 버전 선택 페이지 에서 사용자가 선택한 버전 ID zustand 상태 업데이트
  - 페이지 선택 페이지 에서 사용자가 선택한 페이지 ID zustand 상태 업데이트
  - 비교 페이지 이동 전 사용자의 입력 정보를 zustand 에서 받아와 서버로 페이지 비교 API 호출

- **2.** @doitchuu 개발해주신 공통 컴포넌트를 적용하여서 페이지 레이아웃 개발
  zustand 상태 정상 업데이트 확인 및 페이지간 데이터 흐름 확인 

<br />

## 어떻게 해결했나요?

- 각각의 페이지에서 입력하는 데이터 정보에 따라서 zustand 스토어를 4개로 분리하였다.
- 비교 요청 API 호출 전 사용자가 현재 입력한 파일키, 버전 정보, 페이지 ID를 zustand 상태에서 가져온다.

- 유틸 함수 추가
  - URI 파일 키 파싱 함수 `getFileKeyFromURI`
  - 프로젝트 버전 이름 변환 함수 `convertLabel`
  - 사용자 인증 코드 파싱 함수 `getAuthFromURI`
  - API 요청 URI 반환 함수 `generateApiUri`

<br />

  - CSR에서 accessToken, refreshToken을 사용한 로그인 유지 기능 필요.  @kyeongjun-ko
   - fresh token을 사용한 페이지 이동간  로그인 유지 기능 이슈 카드 추가 및 개발 필요. @kyeongjun-ko 2  
  

<br />

## 잠깐! 확인해보셨나요?

- [x]  셀프 리뷰는 완료하셨나요?
- [x]  가장 최신 브랜치를 pull했나요?
- [x]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [x]  코드 컨벤션을 모두 지켰나요?
- [x]  적절한 라벨이 있나요?
- [x]  assignee가 있나요?

<br />

## Attachment(선택사항) 
- URI 페이지 ~ 비교 페이지 전까지 zustand 로 부터 상태 업데이트 및  페이지간 데이터 흐름 확인했습니다.
- 정상 작동 확인
  ![Feb-07-2024 13-31-45](https://github.com/Figci/Figci-Client/assets/95596243/4e461bd1-b17a-4c95-bdef-6792fccbe87b)

2024-02-07 16:31 UTC, tjd985 requested changes
코멘트 확인 부탁드립니다!

2024-02-07 16:31 UTC, tjd985 commented on src/components/ProjectVersion/index.jsx
> +
- `P1`
여기 개행은 지워주셔도 될 것 같습니다!

2024-02-07 16:31 UTC, tjd985 commented on src/components/shared/BottomNavigator.jsx
> +  flex-direction: row;
- `P3`
`flex-direction`은 작성 안할 시 `row`로 기본값이 할당이 되는데 삭제하는것으로 통일하는 것에 대해서
경준님은 어떻게 생각하시나요!

2024-02-07 16:31 UTC, tjd985 commented on src/components/shared/Select.jsx
> +  margin-right: 2rem;
- `P1`
기존의 코드들을 보면 `font-size`를 제외한 나머지는 `px`을 사용하는것으로 보이는데
통일해주시면 좋을 것 같습니다!

2024-02-07 16:31 UTC, tjd985 commented on src/components/shared/Select.jsx
> +            {select.options && select.options}
- `P1`
```suggestion
            {select.options}
```
동일 할 것 같습니다!

2024-02-07 16:31 UTC, tjd985 commented on src/components/ProjectVersion/index.jsx
> +          allDates &&
`allDates`는 기본값이 빈 배열이라서 항상 true가 나올 것 같습니다!

2024-02-07 16:31 UTC, tjd985 commented on src/components/ProjectVersion/index.jsx
> +import { getPages } from "../../services/pages";
- `P1`
개행 부탁드립니다!

2024-02-07 16:31 UTC, tjd985 commented on src/components/utils/convertLabel.js
> +export default convertLabel;
해당 함수에 대해서 설명 한번만 부탁드립니다! 🙇🏻‍♂️

2024-02-07 16:31 UTC, tjd985 commented on src/services/pages.js
> +  const fileKey = import.meta.env.VITE_FIGMA_DEV_FILE_KEY;
- `P1`
개발할때 사용하셨던 목데이터로 보이는데 맞나요?
맞다면 삭제부탁드립니다!

2024-02-07 16:31 UTC, tjd985 commented on src/components/ProjectPage/index.jsx
> +    const { fileKey, beforeVersion, afterVersion } = getStatus();
- `P2`
`state`를 사용할 때 마다 따로 만들어서 코드의 가독성이 조금 떨어지는 것 같습니다!
혹시 `getState`를 따로 만들어서 정규화를 하신 이유가 있을까요?

2024-02-07 16:45 UTC, kyeongjun-ko commented on src/components/utils/convertLabel.js
> +export default convertLabel;
10:10:10Z 라는 형태의 문자열을 HH:MM 타입의 문자열로 변환하는 함수로
버전 이름이 없어서 생성 날짜가 default 로 들어가는 버전의 이름을 변환하기 위해 만들었습니다.

- `/`는 특수문자를 문자열로 인식하기 위해서 사용되는 기호이고
- `\d {2}:`  에서  \d 는 digit 숫자를 의미하고 {2} 는 2개로 2개의 숫자뒤에 `:` 이 붙은 문자열입니다. ex) 10:
- `match()`는 문자열이 정규식과 일치하는 부분을 반환하고, 일치 하지 않는 경우 null을 반환합니다.
- `/\b` 는 숫자와 문자열을 구분한다는 뜻으로 정확하게 일치하는 문자열을 찾기위해 사용했지만 없어도 작동됩니다.

`/\d{2}:\d{2}:\d{2}Z/` 와 의미가 같습니다.

2024-02-07 16:51 UTC, kyeongjun-ko commented on src/components/ProjectPage/index.jsx
> +    const { fileKey, beforeVersion, afterVersion } = getStatus();
`zustand` 에서 선언한 상태 변수를 사용하기 위해서 명시적으로 사용했는데
상태를 없데이트 하지않고 읽기만 하면 getState() 를 사용하지 않아도 된다고 합니다.

상태 변경이 없는 `zustand ` 변수들은 `const { status } = usePageStatusStore(); `
바로 스토어 함수를 실행해서 구조분해 할당으로  상태 변수를 사용하도록 하겠습니다.

2024-02-07 16:51 UTC, kyeongjun-ko commented on src/services/pages.js
> +  const fileKey = import.meta.env.VITE_FIGMA_DEV_FILE_KEY;
네 바로 반영하겠습니다.

2024-02-07 16:51 UTC, kyeongjun-ko commented on src/components/ProjectVersion/index.jsx
> +import { getPages } from "../../services/pages";
컴포넌트와 외부 유틸함수 개행 컨벤션 확인 하겠습니다.

2024-02-07 16:53 UTC, kyeongjun-ko commented on src/components/ProjectVersion/index.jsx
> +          allDates &&
빈배열은 항상 트루시를 값이라는걸 놓치고 있었네요.
allDates.length 로 값의 존재 여부를 판별하도록 하겠습니다.

2024-02-07 16:59 UTC, doitchuu requested changes
코멘트 반영 부탁드립니다 👍  고생 많으셨습니다 :)

2024-02-07 16:59 UTC, doitchuu commented on src/components/NewProject/index.jsx
> +  };
P2: 관련 함수 로직 간 묶어주는 게 어떨까요? `Store`에 저장하는 함수 로직과 이벤트 핸들러 함수 로직의 순서를 
같이 묶어주면 더 좋을 것 같습니다 👍 

```suggestion
  const setAuthStore = authParams => {
    useAuthStore.getState().setAuth(authParams);
  };

  const updateFileKey = newFileKey => {
    usePageStatusStore.getState().setStatus({ fileKey: newFileKey });
  };

  const updateVersions = newVersions => {
    useProjectVersionStore.getState().setVersion(newVersions);
  };

  const handleModalClick = ev => {
    ev.preventDefault();

    setIsModalOpened(false);
  };

  const handleInputChange = ev => {
    setInputValue(ev.target.value);
  };

  const onClickSubmitButton = async ev => {
    ev.preventDefault();

    const fileKey = getFileKeyFromURI(inputValue);

    updateFileKey(fileKey);
    updateVersions(await getVersions(fileKey));

    navigate("/version");
  };
```

2024-02-07 16:59 UTC, doitchuu commented on src/components/ProjectVersion/index.jsx
> +import usePageStatusStore from "../../../store/projectInit";
P1: 동일한 경로에서 사용되는 컴포넌트, Store 간에 묶어줘도 좋을 것 같습니다 👍 

```suggestion
import { BottomNavigator, Title, Select, Modal, Loading } from "../shared";
import { getPages, convertLabel } from "../../services";
import { useProjectVersionStore, usePageListStore, usePageStatusStore } from "../../../store";
```

2024-02-07 16:59 UTC, doitchuu commented on src/components/ProjectVersion/index.jsx
> +      { text: "다음", usingCase: "solid", handleClick: onClickSubmitButton },
P1: 이벤트 핸들러 함수라는 네이밍에 적합하게 작성해주시면 좋을 것 같습니다 :)

```suggestion
      { text: "이전", usingCase: "solid", handleClick: handleClickPrevButton },
      { text: "다음", usingCase: "solid", handleClick: handleSubmitButton },
```

2024-02-07 16:59 UTC, doitchuu commented on src/components/ProjectVersion/index.jsx
> +          <Select selectInfo={nextData} />
P1: 이전 버전/ 다음 버전에 대한 데이터가 들어간다는 prop명이 명시적으로 들어가면 좋을 것 같아요.
Data는 일반적인 대명사라 직관적이지 않을 듯 합니다 😂

```suggestion
          <Select selectInfo={beforeVersion} />
          <Select selectInfo={afterVersion} />
```

2024-02-07 16:59 UTC, doitchuu commented on src/components/ProjectVersion/index.jsx
> +  width: 100%;
P1: `display` 속성끼리는 같은 속성이라 같이 붙여주시는 게 좋을 것 같습니다! :)

```suggestion
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: flex-start;
  align-items: flex-end;
```

2024-02-07 16:59 UTC, doitchuu commented on src/components/shared/BottomNavigator.jsx
>    border-top: 2px solid;
P2: 색상도 명시적으로 기입해주시면 좋을 것 같아요!

```suggestion
  border-top: 2px solid #000000;
```

2024-02-07 16:59 UTC, doitchuu commented on src/components/shared/Select.jsx
> +  margin-right: 2rem;
P1: `margin` 값은 `px`로 통일해서 사용하고 있어요. 해당 부분은 통일해서 작성 부탁드려요!

```suggestion
  margin-right: 32px;
```

2024-02-07 16:59 UTC, doitchuu commented on src/components/utils/convertLabel.js
> +export default convertLabel;
P1: 함수 형식은 화살표 함수로 작성해주시면 좋을 것 같습니다:)

2024-02-07 16:59 UTC, doitchuu commented on src/components/utils/getAuthFromURI.js
> +export default getAuthFromURI;
해당 함수도 화살표 함수로 작성 부탁드립니다!

2024-02-07 16:59 UTC, doitchuu commented on store/projectPage.js
> +const usePageListStore = create(devtools(pageStore));
P1: 해당 부분도 `devtools`를 지워주시면 좋을 것 같아요!

2024-02-07 16:59 UTC, doitchuu commented on src/services/pages.js
> +const getPageDiff = () => {};
혹시 이 함수는 어떤 역할을 하는 함수인 지 설명을 들을 수 있을까요?

2024-02-07 16:59 UTC, doitchuu commented on store/projectAuth.js
> +import { devtools } from "zustand/middleware";
```suggestion
```

2024-02-07 16:59 UTC, doitchuu commented on src/components/utils/convertLabel.js
> +export default convertLabel;
P3: 사용자 친화적인 라벨링을 해준다면 버전명이 시간 정보라면 오후 12시 23분 32초 라던지 시간에 대한 정보를 
조금 더 친절한 워딩으로 바꿔주는 로직이 있어도 좋을 것 같습니다 :)

추가적으로 함수명도 시간 정보를 변환해준다는 느낌을 줄 수 있는 함수명이면 좋을 것 같아요 👍 
예를 들어 `convertKoreaTime`이라던지 조금 더 명시적인 함수명이면 좋을 것 같습니다 ! 🥲

2024-02-07 16:59 UTC, doitchuu commented on src/components/ProjectVersion/index.jsx
> +  };
P2: 매직 넘버는 지양하면 좋을 것 같습니다 🤣

```suggestion
  const BACK = -1;

  const onClickBackToProject = ev => {
    ev.preventDefault();

    usePageStatusStore.getState().clearProject();

    navigate(BACK);
  };
```

2024-02-07 17:44 UTC, doitchuu reviewed
리뷰 추가로 남겼습니다 :) 확인 부탁드려요 😀

2024-02-07 17:44 UTC, doitchuu commented on src/components/ProjectVersion/index.jsx
> +      afterVersion: nextVersion,
P3: 이름을 통일하면 좋을 것 같습니다 👍
```suggestion
  const updateVersions = (beforeVersion, afterVersion) => {
    usePageStatusStore.getState().setStatus({
      beforeVersion,
      afterVersion,
```

2024-02-08 04:40 UTC, kyeongjun-ko commented on store/projectPage.js
> +    allPages: [],
`byPageIds` , `allPageIds` 는 어떠실까요?

2024-02-08 04:41 UTC, kyeongjun-ko commented on store/projectInit.js
> +const usePageStatusStore = create(devtools(initStore));
개발 환경 테스트시에만 `devtools`를 사용하고
main 에 push 할때는 삭제하겠습니다.

2024-02-08 04:48 UTC, kyeongjun-ko commented on src/components/utils/getFileKeyFromURI.js
> +export default getFileKeyFromURI;
URI 로부터 받아오는 로직에서는 useSearchParams() 를 사용했습니다.
현재 로직의 경우는 사용자의 입력값으로 부터 파싱해야 하기에 함수를 만들었습니다.

2024-02-08 04:49 UTC, kyeongjun-ko commented on src/services/pages.js
> +    };
DB 스키마 구조 변경 후부터 서버로부터 배열 형태를 받아오기에 함수를 삭제했습니다.

2024-02-08 04:50 UTC, kyeongjun-ko commented on src/components/shared/BottomNavigator.jsx
> +  flex-direction: row;
네 동감합니다. 기본값(row)인 경우에 flex-direction은 사용하지 않겠습니다.

2024-02-08 05:11 UTC, kyeongjun-ko commented on src/components/NewProject/index.jsx
> +      { text: "다음", usingCase: "solid", handleClick: onClickSubmitButton },
다음과 같은 형식으로 이벤트 함수명을 지었습니다.
handle + `이벤트 명` + `데이터 정보`
변경된 이벤트 함수명은 아래와 같습니다.

Versions 컴포넌트 : `onClickSubmitButton` => `handleSubmitURI`
NewProject 컴포넌트 : `onClickSubmitButton` => `handleSubmitVersion`

2024-02-08 05:30 UTC, kyeongjun-ko commented on src/components/ProjectVersion/index.jsx
> +      { text: "다음", usingCase: "solid", handleClick: onClickSubmitButton },
아래와 같은 형식으로 함수명 변경하였습니다.
`handle` + `이벤트 타입` + `엘리먼트 타입`
변경된 이벤트 함수명은 아래와 같습니다.

onClickBackToProject => handleClickPrevButton
onClickSubmitButton => handleSubmitNextButton

2024-02-08 05:33 UTC, kyeongjun-ko commented on src/components/ProjectVersion/index.jsx
> +          <Select selectInfo={nextData} />
아래와 같이 변수명 수정했습니다.
prevData => prevVersionForm
nextData => nextVersionForm

2024-02-08 05:36 UTC, kyeongjun-ko commented on src/services/pages.js
> +const getPageDiff = () => {};
서버로부터 변경 트리를 받아오는 로직으로 아직 서버 API와 연결 전이라
빈 함수를 미리 만들어 두었습니다.

2024-02-08 07:11 UTC, doitchuu reviewed
해당 코멘트 반영 부탁드립니다 👍 
리뷰 내용 반영하시느라 고생이 많으십니다!

2024-02-08 07:15 UTC, doitchuu reviewed
추가 코멘트도 작성해두었습니다 :) 확인해주시면 감사하겠습니다

2024-02-08 07:15 UTC, doitchuu commented on src/components/ProjectVersion/index.jsx
> +  const dateFilter = () => {
P1: 함수명은 동사형으로 변경해주시면 감사하겠습니다 👍 

```suggestion
  const filterLaterDates = () => {
```

2024-02-08 07:28 UTC, tjd985 reviewed
코멘트 확인 부탁드립니다!

2024-02-08 07:28 UTC, tjd985 commented on src/components/NewProject/index.jsx
> +    const fileId = getFileKeyFromURI(inputValue);
- `P1`
함수는 `getFileKey`라고 작성이 되어져 있는데, 변수는 `fileId`로 받고있습니다!
`key`와 `id`를 혼용하고 계신것 같습니다!

용어를 `project`와 `key`로 고정하는 것이 어떨까요?

2024-02-08 07:28 UTC, tjd985 commented on src/components/ProjectPage/index.jsx
> +  };
- `P1`
현재 이 함수는 비동기로직을 처리하는 부분이 보이지 않습니다!
`async`는 삭제해주어도 될것 같네요

2024-02-08 07:28 UTC, tjd985 commented on src/components/ProjectPage/index.jsx
> +              const [nodeId, nodeName] = e[0];
- `P2`
`for..in`으로 작성 가능하지 않을까 싶습니다!
경준님 생각은 어떠세요?

2024-02-08 07:28 UTC, tjd985 commented on src/components/ProjectVersion/index.jsx
> +          )),
위 코멘트와 동일합니다!

2024-02-08 07:28 UTC, tjd985 commented on src/components/ProjectVersion/index.jsx
> +            </option>
위 코멘트와 동일합니다!

2024-02-08 07:28 UTC, tjd985 commented on src/components/utils/getAuthFromURI.js
> +export default getAuthFromURI;
- `P1`
기능이 중복되어서 해당 모듈은 삭제해도 될것 같습니다!

2024-02-08 07:28 UTC, tjd985 commented on src/services/pages.js
> +export { getPages, getPageDiff };
- `P2`
서버에서는 `diffingResult`라는 변수명으로 보내고 있으므로

```suggestion
export { getPages, getDiffingResult };
```
로 통일하면 더 좋을 것 같습니다

2024-02-08 07:28 UTC, tjd985 commented on store/projectAuth.js
> +    },
- `P2`
`auth`를 제거해서 `depth`를 낮추면 복잡도가 더 적어질 것 같습니다!

2024-02-08 10:02 UTC, kyeongjun-ko commented on src/components/ProjectVersion/index.jsx
> +  const dateFilter = () => {
함수명 변경했습니다.
dateFilter => filterNextDates

2024-02-08 10:06 UTC, kyeongjun-ko commented on src/components/ProjectPage/index.jsx
> +              const [nodeId, nodeName] = e[0];
함수 바디부분에  렌더 목록을 반환하는 함수를 만들었습니다.
```javascript
// 드롭다운 option 리스트 목록
const selectOptionRenderList = () => {
    const renderList = [];

    for (const pageId in pageList) {
      const pageNode = pageList[pageId];

      renderList.push(
        <option key={pageNode["node_id"]} value={pageNode["node_id"]}>
          {pageNode.name}
        </option>
      );
    }

    return renderList;
  };
```

```javascript
selects: [
        {
          id: "pageSelection",
          value: "pageSelection",
          options: pageList && selectOptionRenderList(),
          onChange: onChangeHandler,
        },
      ],
```

2024-02-08 10:07 UTC, kyeongjun-ko commented on store/projectAuth.js
> +    },
verifyToken 구현시 필요한 부분있을때 수정하도록 하겠습니다.

2024-02-08 10:43 UTC, tjd985 approved these changes
확인했습니다!
고생하셨습니다 👍🏻

2024-02-08 10:44 UTC, doitchuu approved these changes
로직이 많이 추가되었네요 👍 
고생 많으셨습니다!! 🙏

2024-02-08 10:44 UTC, merged