Feat: 비교 페이지 - 버전 재선택 & 새 프로젝트 비교 팝업
Figci/Figci-Client pull request #31
Opened 2024-02-11 14:38 UTC by tjd985

## Fix (이슈 번호)
closes #9 

<br />

## 해결하려던 문제를 알려주세요!
1. 버전 재선택 클릭시 모달창이 나와야 합니다.
2. 새 프로젝트 비교를 클릭시 동일하게 모달창이 나와야 합니다.

<br />

## 어떻게 해결했나요?
```js
// diffingResult페이지까지 도달했을 경우 status 상태 예시
const status = {
  projectUrl: "http://www.figci.com",
  porjectKey: "awndjnwj",
  beforeDate: "123",
  beforeVersionId: "123:123",
  afterDate: "456",
  afterVersionId: "456:456",
  pageId: "789:789"
}
```
클릭 시 해당 모달창을 띄운 뒤, 새 프로젝트 비교를 클릭 시 다시 프로젝트 URL을 입력하는 컴포넌트로 이동이 되고, 기존에 비교하던 컴포넌트 URL을 `default value`로 셋팅합니다.
이후 global status로 관리하던 모든 `project status`를 초기화 해줍니다.
버전 재선색을 클릭 할 시 비교할 프로젝트 버전을 고르는 컴포넌트로 이동이 되고, project status로 관리하던 `version`을 초기화 해줍니다.

```js
// 버전 재선택을 눌러서 버전선택 페이지로 이동했을 경우 status상태
const status = {
  projectUrl: "http://www.figci.com",
  porjectKey: "awndjnwj",
  beforeDate: null,
  beforeVersionId: null,
  afterDate: null,
  afterVersionId: null,
  pageId: null
}
```

```js
// 새 프로젝트 비교하기 를 눌러서 새 페이지로 이동했을 경우 status상태
const status = {
  projectUrl: null,
  porjectKey: null,
  beforeDate: null,
  beforeVersionId: null,
  afterDate: null,
  afterVersionId: null,
  pageId: null
}
```

<br/>

### 만났던 에러
이번 작업을 하던 중 `Description`을 공통컴포넌트 화 했습니다.
해당 작업을 진행하던 중 prop으로 받은 text들을 `\n` 마다 줄바꿈을 해주기 위해서 text를  split("\\n")을 한 뒤 해당 Array를 map을 돌면서 fragment component(`<></>`)로 만들어 주었습니다.
이때 반복문을 돌기 때문에 key값을 주입해주어야 하는데, 일반적으로 우리가 사용하던 fragment component로는 key값을 부여할 수 없었습니다.
따라서 Fragment태그를 명시적인 <Fragment>구문으로 작성해서 key값을 부여했습니다.
[Frament 컴포넌트](https://react-ko.dev/reference/react/Fragment)

- 원래 알고있던 <></>로 작성을 했을 때
![image](https://github.com/Figci/Figci-Client/assets/48385389/41c7cab6-7d8b-4b66-ab11-026353dece33)

- 명시적인 Fragment구문으로 수정한 결과
![image](https://github.com/Figci/Figci-Client/assets/48385389/f114085d-b8c8-46aa-9736-dd74ff6fee98)

<br />

## 우려사항이 있나요?(선택사항)
- 고유한 key값을 부여하기 위해서 `nanoid`라는 라이브러리를 설치했습니다. 꼭 참고 바랍니다❗️
([nanoid](https://github.com/ai/nanoid))
- `Description`을 컴포넌트 화 했습니다❗️
- 기존의 global state에서 다른 스토어의 메서드끼리 이름이 겹치는 것을 발견하여, `projectInit.js`애 있는 clear메서드들 `postfix`로
`status` 를 붙혔습니다❗️
- `projectStatus` 스토어에 사용자가 입력한 URL을 받는 `projectUrl`프로퍼티를 추가했습니다❗️
- `404 페이지`를 구현했습니다

<br />

## 잠깐! 확인해보셨나요?

- [X]  셀프 리뷰는 완료하셨나요?
- [X]  가장 최신 브랜치를 pull했나요?
- [X]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [X]  코드 컨벤션을 모두 지켰나요?
- [X]  적절한 라벨이 있나요?
- [X]  assignee가 있나요?

<br />

## Attachment(선택사항) 
- 404 페이지
<img width="1440" alt="image" src="https://github.com/Figci/Figci-Client/assets/48385389/aacd4038-af40-4fb3-a677-6c107ae4362c">

<br/>
<br/>

- 새 프로젝트 비교 클릭 시
<img width="1440" alt="image" src="https://github.com/Figci/Figci-Client/assets/48385389/a18e3788-5574-413b-a831-03e3ee6456f9">

<br/>
<br/>

- 비교할래요! 클릭해서 `/New`로 이동시 방금 비교한 프로젝트 URL이 `default value`로 set되어져있는 모습
<img width="1440" alt="image" src="https://github.com/Figci/Figci-Client/assets/48385389/d76b0d40-8bab-48ba-b67c-30f1a96822d2">

2024-02-11 15:31 UTC, doitchuu reviewed
리뷰 남겼습니다. 코멘트 반영 부탁드려요 👍 
리액트 내 `map` 메소드 사용 시 넘어갈 수도 있는 key값의 중복을 막기 위해 nanoid 라이브러리를 활용하신 점 좋네요!
변수명이나 로직을 단순히 쓰시는 것 많이 참고하겠습니다. 고생하셨습니다 🙏

2024-02-11 15:31 UTC, doitchuu commented on services/getCommonPages.js
> +export default getCommonPages;
변수명이 직관적이라 좋네요! 👍

2024-02-11 15:31 UTC, doitchuu commented on src/components/Onboarding/index.jsx
> +        />
`Description` 컴포넌트로 정의하니 코드가 깔끔해져서 좋네요 👍

2024-02-11 15:31 UTC, doitchuu commented on src/components/shared/Description.jsx
> +        <React.Fragment key={nanoid(10)}>
`nanoid`로 `key` 값 중복을 막아줘 더 좋은 것 같습니다 👍

2024-02-11 15:31 UTC, doitchuu commented on src/components/DiffingResult/index.jsx
> +              className="reVersion"
P1: 클래스명은 케밥케이스로 통일 부탁드립니다!

2024-02-11 15:31 UTC, doitchuu commented on src/components/Sidebar/index.jsx
> +              text="비교하기 버튼을 누루면 현재 화면에서 벗어나게 됩니다.\n보고계신 정보는 저장되지 않아요."
P1: 누르면으로 오타 수정 부탁드려요.

```suggestion
              text="비교하기 버튼을 누르면 현재 화면에서 벗어나게 됩니다.\n보고계신 정보는 저장되지 않아요."
```

2024-02-11 15:53 UTC, tjd985 commented on src/components/DiffingResult/index.jsx
> +              className="reVersion"
수정하겠습니다!

2024-02-11 15:54 UTC, tjd985 commented on src/components/Sidebar/index.jsx
> +              text="비교하기 버튼을 누루면 현재 화면에서 벗어나게 됩니다.\n보고계신 정보는 저장되지 않아요."
앗...! 바로 수정하겠습니다

2024-02-11 22:05 UTC, kyeongjun-ko commented on package.json
> +    "nanoid": "^5.0.5",
P3: 리액트에서 반복 렌더링시 고유한 key값을 정의하기 위해 항상 고민했는데 임의의 변수를 만들어주는 라이브러리가 있었군요 👍

2024-02-11 22:17 UTC, kyeongjun-ko commented on src/components/App.jsx
>          <Route path="/result" element={<DiffingResult />} />
P1: Routes 컴포넌트들을 위에서부터 쭉 찾아서 내려오다가
매칭되는 라우터가 없을때 에러 페이지로 이동해야 하기 떄문에
`/result` 밑에 오는게 맞을것 같습니다

2024-02-11 22:18 UTC, kyeongjun-ko commented on assets/not-found-image.png
P3: 저작권 없으면서도 예쁜 이미지를 찾으셨네요 👍

2024-02-11 22:32 UTC, kyeongjun-ko commented on src/components/DiffingResult/index.jsx
> +              className="close"
위의 클래스 명처럼 블럭을 명시하면 좋겠네요
아니면 `블럭__요소--수식` 의 BEM 형태로
`reselection__button--next `또는
`reversion__button--next` 로 지을수도 있겠군요

2024-02-11 22:40 UTC, kyeongjun-ko commented on src/components/NewProject/index.jsx
> +    setVersion(allVersions.content);
P3: set 함수가 지역상태를 없데이트 하는건지
글로벌 스토어 상태를 업데이트 하는지 헷갈리네요..

postFix 형태로 status 또는 store 라고 명시하면 좋겠네요
어떻게 생각하시나요? @tjd985  @doitchuu

2024-02-11 22:46 UTC, kyeongjun-ko commented on src/components/NotFound/index.jsx
> +          handleClick={() => {
P3: 버튼 default 타입이 submit이라서  바로 해당 페이지로 redirect 될것 같은데 
`preventDefault()` 호출하지 않아도 홈으로 redirect 가 잘되는지 궁금하네요
```
const handleButtonBackHome = ev => {
    ev.preventDefault();

    navigate("/");
};
```

2024-02-11 22:56 UTC, kyeongjun-ko commented on src/components/Sidebar/index.jsx
>    const handleNewProjectModalOpen = ev => {
`handle + 명사 + 동사(이벤트)` 나 `handle + 동사(이벤트) + 명사` 형태로 통일하면 좋겠어요
`handleProjectModalClick` || `handleClickProjectModal` 어떠신가요?

2024-02-11 23:07 UTC, kyeongjun-ko commented on src/components/Sidebar/index.jsx
> +            <h3 className="title-number"> {framesInfo.frameCount}</h3>
class 네이밍 규칙이 있으면 좋겠습니다.
다른 생각 있다면 의견 공유주세요 @tjd985 @doitchuu 

`sidebar__frame-list--theme` || `frame-list--theme`
`sidebar__frame-list--title` || `frame-list--title`
`sidebar__frame-list--title-number` || `frame-list--title-number`
`sidebar__frame-list--content` || `frame-list--content`

2024-02-11 23:35 UTC, kyeongjun-ko commented on src/components/Sidebar/index.jsx
> +                }`}
P3: className 선언부가 조금 부자연스러워 보이네요
조건을 만족하는 경우만 활성화 시키고 싶은거니
만족하는 경우만 생각할수도 있지 않을까요?..

2024-02-11 23:38 UTC, kyeongjun-ko requested changes
리뷰 확인 부탁드립니다

2024-02-12 04:36 UTC, tjd985 commented on package.json
> +    "nanoid": "^5.0.5",
넵 맞습니다!
아이디값을 따로 줄것이 없을 떄 사용하면 좋을 것 같아요

2024-02-12 04:37 UTC, tjd985 commented on src/components/App.jsx
>          <Route path="/result" element={<DiffingResult />} />
`404페이지`에서도 `header`를 띄우기 위해서 `Layout`내부에 위치시켰고, `/result`로 이동하는 것 또한 특이사항 없는것 확인했습니다!

2024-02-12 04:39 UTC, tjd985 commented on src/components/DiffingResult/index.jsx
> +              className="close"
`close-button`으로 수정하겠습니다!

2024-02-12 04:43 UTC, tjd985 commented on src/components/NewProject/index.jsx
> +    setVersion(allVersions.content);
`setVersionStore`는 스토어에 버전리스트들을 set하는 의미에서는 조금 벗어난 변수명 같은 느낌이 드네요!
아니면 `setVersionList`는 어떠세요?

2024-02-12 04:45 UTC, tjd985 commented on src/components/NotFound/index.jsx
> +          handleClick={() => {
`form`으로 감싸져 있는 버튼이 아니기 떄문에 submit이벤트는 발생하지 않을 것 같습니다!
따라서 `redirect`도 정상적으로 잘 작동하구요! 😃

2024-02-12 04:48 UTC, tjd985 commented on src/components/Sidebar/index.jsx
> +            <h3 className="title-number"> {framesInfo.frameCount}</h3>
통일된 클래스 명을 가지면 좋을것 같다는 의견은 매우 동감합니다!
다만, 현재 저희의 코드상 `projectVersion.jsx`에서 `className`을 이용하는 부분이 있는데
해당 부분도 그렇게 된다면 같이 수정해야 할 것 같습니다! 😀

2024-02-12 05:02 UTC, tjd985 commented on src/components/Sidebar/index.jsx
> +                }`}
해당 부분은 클릭된 프레임이 바뀔 때 마다, 클릭된 `frame`에는 강조표시를 하기 위해서 위처럼 작성이 되었습니다!
매번 리렌더링이 일어날 때 마다 `frame`들을 순회하면서 클릭된 프레임 아이디에 `active`를 추가한 뒤, 렌더링을 할 때 다시한번 순회를 도는 것보다는, 한번에 순회하면서 렌더링과, 클래스 `active`를 추가하는 것이 시간복잡도에 있어서 미약하게 나마 도움이 되지 않을 까 해서 작성했습니다!

경준님의 방식을 자세하게 들어보고 싶습니다! 😄

2024-02-12 05:13 UTC, kyeongjun-ko commented on src/components/NotFound/index.jsx
> +          handleClick={() => {
form 메서드로 감싸져있지 않으면
submit 이벤트는 발생하지 않는군요

2024-02-12 05:17 UTC, kyeongjun-ko commented on src/components/Sidebar/index.jsx
> +                }`}
className 에 식이 들어가있는게 낯설어 보였는데 성호님 리뷰와 함께 보니
프레임 목록중 현재 선택된 프레임을 표시하기 위한 역할이라고 이해했습니다.

2024-02-12 05:19 UTC, doitchuu approved these changes
Description 컴포넌트를 쓰니 코드양이 줄어드는 곳이 많네요! 👍 
공통 컴포넌트로 잘 분리하신 것 같습니다 👍

2024-02-12 05:19 UTC, doitchuu commented on src/components/ProjectPage/index.jsx
> +  const { setStatus, clearPageStatus } = usePageStatusStore(state => state);
변수명이 명확해져서 좋네요 👍

2024-02-12 05:19 UTC, doitchuu commented on src/components/Sidebar/index.jsx
> +            <h3 className="title-number"> {framesInfo.frameCount}</h3>
기존대로 케밥 케이스로 가져가면 좋을 것 같습니다 👍

2024-02-12 05:19 UTC, kyeongjun-ko commented on src/components/Sidebar/index.jsx
> +                setIsClickedNewPorject(false);
P3: 아래 버튼에서 preventDefault() 선언후 개행하였는데
이곳에서는 개행하지 않은 이유가 따로 있는지 궁금합니다.

2024-02-12 05:20 UTC, kyeongjun-ko submitted a review, later dismissed
코멘트 반영사항 확인했습니다. 수고하셨습니다.

2024-02-12 05:23 UTC, doitchuu approved these changes

2024-02-12 05:24 UTC, kyeongjun-ko approved these changes
확인했습니다! 고생하셨어요 성호님

2024-02-12 05:25 UTC, tjd985 commented on src/components/Sidebar/index.jsx
> +                setIsClickedNewPorject(false);
제가 놓친 것 같습니다 수정하겠습니다~
꼼꼼하게 봐주셔서 감사합니다🙏🏻

2024-02-12 05:25 UTC, merged