Feature: Google Tag Manager 를 사용한 Googla Analytics 적용
Figci/Figci-Client pull request #56
Opened 2024-04-24 13:30 UTC by kyeongjun-ko

## Fix (이슈 번호)

none

<br />

## 해결하려던 문제를 알려주세요!

Figci 홈페이지 사용자 추이를 확인하기 위해서 Figci 구글 계정에 Google Tag Manager를 등록 했습니다.

<br />

## 어떻게 해결했나요?

> Google Tag Manager ID 발급하였습니다.
> Google Analytics 계정 생성하였습니다.
위와 관련 내용은 보안 문제로 팀 슬랙에 공유하였습니다.

<br />

## 우려사항이 있나요?(선택사항)

> 추후에[ Google Task Assi](https://tagassistant.google.com/) 에서 사용자 이벤트를 추가해서 더욱 상세한 사용자의 홈페이지 사용 이력을 확인 할 수 있습니다. Ex) 비교버튼 클릭 횟수, 비교 버전

<br />

## 잠깐! 확인해보셨나요?

- [x]  셀프 리뷰는 완료하셨나요?
- [x]  가장 최신 브랜치를 pull했나요?
- [x]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [x]  코드 컨벤션을 모두 지켰나요?
- [x]  적절한 라벨이 있나요?
- [x]  assignee가 있나요?

<br />

## Attachment(선택사항) 

>  Netlify 에 환경변수에 GTM Id를 추가하였습니다.
![image](https://github.com/Figci/Figci-Client/assets/95596243/a8a8362a-5d51-451a-b743-1157aa7bfff9)

<br />

2024-04-24 18:05 UTC, doitchuu submitted a review, later dismissed
배포 후에 다시 다같이 테스트해보면 좋을 것 같습니다 👍 
고생하셨습니다!

2024-04-24 18:08 UTC, tjd985 requested changes
코멘트 확인 한번만 부탁드리겠습니다~!!

2024-04-24 18:08 UTC, tjd985 commented on src/components/DiffingResult/index.jsx
> +        canvasRef.current.requestRenderAll();
요소의 렌더링 위치를 조정한 다음에 다시 그려줌으로써 요소 이동을 구현하셨군요!

2024-04-24 18:08 UTC, tjd985 commented on src/components/DiffingResult/index.jsx
>      newCanvas.on("mouse:wheel", ev => {
- `P2`
선언부와 비즈니스로직은 한칸 개행해주시면 더 좋을 것 같아요!

```suggestion
    const newCanvas = initCanvas();
    
    newCanvas.on("mouse:wheel", ev => {
```

2024-04-25 05:24 UTC, kyeongjun-ko commented on src/components/DiffingResult/index.jsx
> +      ev.e.stopPropagation();
Dom 객체에 이벤트를 추가할때랑 Fabric 객체에 이벤트를 추가할때가 조금 다른데요

Dom 객체에 이벤트를 추가할때는 첫번째 매개변수가 이벤트의 속성과 메서드에 바로 접근할수 있는 반면
Fabric객체에서는 이벤트 객체가 랩핑되서 실제 이벤트객체에 접근하기 위해서는 e라는 속성에 한번더 접근해야 합니다.

```js
// 1. 일반 DOM 객체에 이벤트 핸들러 추가
const element = document.getElementById('myElement');

element.addEventListener('click', ev => {
  console.log('Clicked element:', ev.target);
});

// 2. fabric.js에서 이벤트 핸들러 추가
const canvas = new fabric.Canvas('Canvas');

canvas.on('mouse:down', ev => {
  console.log('Mouse down event:', ev.e.clientX, ev.e.clientY);
});
```

그래서 위 코드에서 1의 실제 이벤트객체는 ev.target 이고
2의 실제 이벤트 객체는 ev.e 입니다.

설명을 덧붙이자면  fabric.js가 캔버스 기반의 라이브러리이며, 자체적인 객체 모델과 이벤트 시스템을 가지고 있기 때문에 이벤트 처리 방식에서도 일반 DOM 객체와 다른 방식을 사용한다고 합니다.

2024-04-25 07:19 UTC, doitchuu commented on src/components/DiffingResult/index.jsx
> +      ev.e.stopPropagation();
설명 감사합니다 ! 해당 내용 기반으로 공부해보겠습니다 :)

2024-04-25 07:20 UTC, doitchuu approved these changes
수정하신 내용 반영했습니다. 고생하셨습니다 👍

2024-04-25 08:31 UTC, tjd985 approved these changes
확인했습니다!!
고생하셨습니다

2024-04-25 10:13 UTC, merged