Feature: Pagenation 기능 구현 (+ 모바일 환경 대응)
Figci/Figci-Client pull request #57
Opened 2024-04-25 13:26 UTC by kyeongjun-ko

## Fix (이슈 번호)

> 이슈 번호를 알려주세요!
closes #12 , closes #13 

<br />

## 해결하려던 문제를 알려주세요!
1. 비교 결과 페이지 - pagination 기능 구현 [Figma Mockup](https://www.figma.com/file/wQ5CcLlM53WqoqcJhMgcfj/240123-Userflow-%2B-feature-detail?type=design&node-id=1000-1391&mode=design&t=NiO2SAB9RgEdkJdM-4)
- [x] 화살표 버튼을 사용해서 프레임 리스트의 프레임을 이동하여서 확인 할 수 있습니다.
- [x] 현재 보고있는 프레임의 index 순서를 좌측 하단의 div에서 확인 할 수 있습니다.

2. 모바일 환경 접속 대응 -  모바일 에러 컴포넌트 작성
- [x] 모바일 환경에서 접속시 모바일 에러 페이지를 렌더링 합니다.
 > 모바일 에러페이지 제작시 Description 재사용 하기위해서 `small` 사이즈 옵션을 추가했습니다.

3. Netlify 404 에러 처리
- [x] Root URL "/"에서 추가로 입력해서 이동할때 Netlify 404 not found 에러 해결 
<img width="962" alt="스크린샷 2024-04-25 오후 3 57 42" src="https://github.com/Figci/Figci-Client/assets/95596243/ecd5cc7c-c0fc-450f-8005-cfe6d10b9a82">

<br />

## 어떻게 해결했나요?

> 문제를 해결한 방법에 대해 명료하게 작성해주세요! 

1. 비교 결과 페이지 - pagination 기능 구현 [Figma Mockup]
-  pagination 숫자 표기를 위해 현재 확인중인 프레임 Index 값을 상태로 관리했습니다.
- 현재 확인중인 프레임의 상태를 업데이트 하는 공통 함수를 작성했습니다.
```js
const changeFrame = frameIndex => {
  const currentFrame = frameList[frameIndex];

  setCurrentPage(frameIndex);
  setFrameId(currentFrame.id);
  setFrameName(currentFrame.name);
};
```

<br />

## 우려사항이 있나요?(선택사항)

2. 모바일 환경 접속 대응 -  모바일 에러 컴포넌트 작성
- 모바일 에러페이지 제작시 Description 재사용 하기위해서 `small` 사이즈 옵션을 추가했습니다.

> 팀원들이 알아야 할 사항이 있으면 알려주세요! 

<br />

## 잠깐! 확인해보셨나요?

- [x]  셀프 리뷰는 완료하셨나요?
- [x]  가장 최신 브랜치를 pull했나요?
- [x]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [x]  코드 컨벤션을 모두 지켰나요?
- [x]  적절한 라벨이 있나요?
- [x]  assignee가 있나요?

<br />

## Attachment(선택사항) 

|Pagenation 테스트|모바일 접속 테스트|
| ---- | ---- |
|![pagination](https://github.com/Figci/Figci-Client/assets/95596243/c72cbf58-2592-4ff5-a3f8-b61325ebe1a2)|![mobileError](https://github.com/Figci/Figci-Client/assets/95596243/c02db4d5-867d-49c9-8404-dc54caf48850)|

<br />

2024-04-25 23:36 UTC, doitchuu requested changes
경준님, 코멘트 확인 부탁드립니다. 
대략적으로 아래와 같은 내용들이라 확인 부탁드립니다 👍 

- css 컨벤션
- 커밋 컨벤션(Feature -> Feat) : 참고차 남겼습니다:)
- 화살표 아이콘 디자인 반영

2024-04-25 23:36 UTC, doitchuu commented on src/components/DiffingResult/index.jsx
> +`;
P1: 해당 부분도 css 컨벤션 맞게 수정 부탁드립니다 :)

2024-04-25 23:36 UTC, doitchuu commented on src/components/MobileErrorPage/index.jsx
> +  margin-top: 40px;
P1: 해당 부분도 CSS 컨벤션대로 수정 부탁드립니다!

2024-04-25 23:36 UTC, doitchuu commented on src/components/MobileErrorPage/index.jsx
> +`;
P1: CSS 컨벤션대로 수정 부탁드립니다!

2024-04-25 23:36 UTC, doitchuu commented on src/components/MobileErrorPage/index.jsx
> +`;
[CSS Convention](https://github.com/necolas/idiomatic-css)

2024-04-25 23:36 UTC, doitchuu commented on src/components/ArrowButton/index.jsx
> +export default ArrowButton;
P1: 경준님, 해당 이전/다음 버튼은 이전 디자인 화면이 있어서 아이콘도 다운받으셔서 쓰시면 될 것 같습니다:)

[비교 결과 페이지 디자인](https://www.figma.com/file/TsOtN6mu4tcht04sIm7nmO/240229-Design?type=design&node-id=1-1357&mode=design&t=4XULGr1OiXxLxsz6-4)

2024-04-25 23:36 UTC, doitchuu commented on src/components/MobileErrorPage/index.jsx
> +  align-items: center;
P1: 해당부분도 동일합니다

2024-04-25 23:36 UTC, doitchuu commented on src/components/MobileErrorPage/index.jsx
> +    font-size: 20px;
P1: 폰트 사이즈는 rem으로 통일해서 사용해주시면 될 것 같습니다

2024-04-25 23:36 UTC, doitchuu commented on src/components/App.jsx
> +      const { userAgent } = navigator;
useEffect로 사이드 이펙트 처리를 해주셨군요 👍

2024-04-25 23:36 UTC, doitchuu commented on src/components/MobileErrorPage/index.jsx
> +        />
공용 컴포넌트로 사용해주셨네요 👍

2024-04-25 23:59 UTC, kyeongjun-ko commented on src/components/MobileErrorPage/index.jsx
> +`;
color, font-weight, text-align 속성 모두 기타 속성으로 분류해서 개행하지 않고 선언했습니다.

2024-04-26 04:09 UTC, tjd985 requested changes
코멘트 확인 부탁드립니다!

2024-04-26 04:09 UTC, tjd985 commented on src/components/App.jsx
> +    };
`userAgent`를 사용해서 사용자가 모바일환경으로 접속했는지를 분간할 수 있네요!

2024-04-26 04:09 UTC, tjd985 commented on src/components/DiffingResult/index.jsx
> +
- P2
두개의 함수가 `+ 1`이냐 `- 1`이냐의 차이만 있는것 같은데
두개의 함수를 id값과 같은 고유한 값에 따른 로직 분기처리를통해서
하나의 함수로 통합하는건 어떨까요!

2024-04-26 05:42 UTC, kyeongjun-ko commented on src/components/DiffingResult/index.jsx
> +
네 좋은 생각인것 같습니다. 중복되는 로직을 함수로 작성해보겠습니다.

2024-04-26 07:10 UTC, tjd985 approved these changes
수정사항 확인했습니다!
고생하셨습니다!! 👍

2024-04-26 07:10 UTC, tjd985 commented on src/components/DiffingResult/index.jsx
> +
피드백 반영 확인 했습니다~~!

2024-04-26 08:13 UTC, doitchuu approved these changes
내용 확인했습니다 :) 
머지 부탁드립니다. 고생 많으셨어요!!

2024-04-26 11:43 UTC, merged