Docs: 리드미 gridFS 내용 및 목차 추가
Figci/Figci-Client pull request #62
Opened 2024-05-16 06:39 UTC by kyeongjun-ko

## Fix (이슈 번호)

none

<br />

## 해결하려던 문제를 알려주세요!

1. 목차를 추가하고 소제목을 한글화 하였습니다.
2. 기능 소개란에 기능 시연 gif 영상을 토글화 하였습니다.
3. 기술 챌린지란에 gridFS 기능 내용이 추가했습니다.
4. 이슈란에 Map 데이터 유지 직렬화 내용 추가했습니다.

<br />

## 어떻게 해결했나요?

- 팀 노션 페이지에 추가된 자료공유 문서를 기반으로 리드미 작성했습니다.
[MongoDB gridFS 기능 활용하기](https://opaque-report-ba5.notion.site/BSON-Map-Javascript-Map-96006695cfc34104baac849ade4f9a1a?pvs=4)
[BSON Map ⚔️ Javascript Map](https://opaque-report-ba5.notion.site/MongoDB-gridFS-2a0fbc276aa8423ea4665c69f4aa3d94?pvs=4)

<br />

## 우려사항이 있나요?(선택사항)

- 기술 챌린지의 각 내용이 너무 긴 경우에 <details> 태그로 토글 형태를 구현하는것을 고려해볼 수 있습니다.

<br />

## 잠깐! 확인해보셨나요?

- [x]  셀프 리뷰는 완료하셨나요?
- [x]  가장 최신 브랜치를 pull했나요?
- [x]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [x]  코드 컨벤션을 모두 지켰나요?
- [x]  적절한 라벨이 있나요?
- [x]  assignee가 있나요?

<br />

2024-05-21 06:57 UTC, doitchuu requested changes
리뷰 확인 부탁드립니다 👍 
리드미 쓰시느라 고생 많으셨습니다!

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +## 💼 Contents
Contents 내 아래 2가지 링크 확인 부탁드려요. 
Preview에서는 링크가 작동이 안되는데 한번 더 확인할 필요가 있을 것 같아요!

[🙅‍♂️ 캔버스에 이벤트가 발생하지 않는다?!](https://github.com/Figci/Figci-Client/blob/0228fda15cbe8d43649b8c1aaf5e58025971ad1a/README.md#%F0%9F%99%85%E2%80%8D%E2%99%82%EF%B8%8F-%EC%BA%94%EB%B2%84%EC%8A%A4%EC%97%90-%EC%9D%B4%EB%B2%A4%ED%8A%B8%EA%B0%80-%EB%B0%9C%EC%83%9D%ED%95%98%EC%A7%80-%EC%95%8A%EB%8A%94%EB%8B%A4)
[❔gridFS Map 데이터가 JSON 직렬화시 데이터가 사라진다?](https://github.com/Figci/Figci-Client/blob/0228fda15cbe8d43649b8c1aaf5e58025971ad1a/README.md#%E2%9D%94-gridfs-map-%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B0%80-json-%EC%A7%81%EB%A0%AC%ED%99%94%EC%8B%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B0%80-%EC%82%AC%EB%9D%BC%EC%A7%84%EB%8B%A4)

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +4. 파일 조회시 `files` 에서 메타데이터를 찾고, 해당 파일의`chunks` 를 합쳐서 파일을 재구성 합니다.
P1: 띄어쓰기 추가 부탁드려요

```suggestion
4. 파일 조회시 `files` 에서 메타데이터를 찾고, 해당 파일의 `chunks` 를 합쳐서 파일을 재구성 합니다.
```

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +두 버전의 피그마 디자인을 비교하기 위해서 피그마 API 로부터 피그마 데이터가 16MB 이상일 경우 MongoDB에 저장 시 에러가 발생했습니다.
이 부분 말이 어색한 것 같아요. 
해당 내용에서는 두 버전의 피그마 디자인을 비교하는 건 중요하지 않은 것 같아서 빼고 
피그마 API로부터 받은 피그마 데이터가 16MB ~~ 발생했습니다. 로 적어도 괜찮을 것 같은데 어떠세요

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +>`Stream`이란 단어에서 유추할수 있듯이 데이터를 끊기지 않고 연속적으로 전송하고 처리하는 방식입니다.
```suggestion
>`Stream`이란 단어에서 유추할 수 있듯이 데이터를 끊기지 않고 연속적으로 전송하고 처리하는 방식입니다.
```

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +    - 청크 단위로 데이터를 처리하는 동시에 변환, 압축등 추가적인 작업을 실시간으로 수행 할 수 있습니다.
```suggestion
    - 청크 단위로 데이터를 처리하는 동시에 변환, 압축 등 추가적인 작업을 실시간으로 수행할 수 있습니다.
```

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +### 4) 문제 해결 : 우리 서비스에서 gridFS 를 어떻게 적용할 수 있을까?
```suggestion
### 4) 문제 해결 : 우리 서비스에서 gridFS를 어떻게 적용할 수 있을까?
```

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +평탄화된 피그마 데이터를 직렬화 하여서 `length` 메서드를 사용해서 구한 파일의 크기에 따라서 <span style="color: #CBF6C1">gridFS 파일 형태로 저장할지 </span>스키마 구조대로 컬렉션에 <span style="color: #FFA5A5">Document 로 저장할지 </span> 분기처리 하였습니다.
요 부분 말이 어색한 듯해요. 하여서 해서 따라서가 중복되서 그런 것 같은데 조금 말이 길어지더라도 해당 내용들에 대한 부가 설명들을 더 넣어서 이해를 도와도 좋을 것 같습니다!

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +4. 결과 반환
저장 시 이후에 : 을 띄어서 적을지 안띄어서 적을 지 하나로 통일해도 좋을 것 같습니다

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +4. 결과 반환
추가로 저장하고와 조회하고도 ,도 통일되면 좋을 것 같아요.

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +    - gridFS 메서드를 호출한곳에서 gridFS Stream의 반환값이 Falsy 일때 에러 핸들링 수행한다.
```suggestion
    - gridFS 메서드를 호출한 곳에서 gridFS Stream의 반환값이 Falsy 일 때 에러 핸들링을 수행한다.
```

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +피그마 데이터에서 분류한 속성들 중에서 디자인 속성을 canvas에 구현하고, 사용자의 마우스 이벤트에 따라서 변경된 영역과 정보를 보여주어야 했기 때문에 이벤트 처리가 용이하고 각 이벤트에 따라서 상호작용할 수 있도록 ```fabric.js``` 를 사용하였습니다.
피그마 데이터에서 어떤 속성들이 분류되어 있고, 이 분류된 것에서 디자인 속성으로 분류된게 뭔지 간략히 (image, line 등) 분류를 조금 적어주어도 좋을 것 같습니다. 

그리고 이벤트 처리가 용이하고 각 이벤트에 따라서 어떤 상호작용을 하는 지가 명시되면 좋을 것 같아요!

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +서버에서 <span style="color: #CBF6C1">**gridFS의 Map 데이터**</span>를 전송할 때 Map 구조가 Object로 직렬화 되면서 Map 내부 데이터가 소실되고 빈 객체를 전달하면서 클라이언트에서 프레임 내부가 빈 화면으로 렌더링 되는 에러가 발생했습니다.
요 부분도 말이 어색한 것 같습니다. 해당 부분도 조금 간결하게 쓰면 좋을 것 같아요!

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +반면에 <span style="color: #FFA5A5">**MongoDB에서 조회한 Map 데이터**</span>를 비교한 결과는 클라이언트에 전송될 때 데이터가 유지된 채 Object로 직렬화 되고 있었습니다. 이에 따라 <span style="color: #CBF6C1">**gridFS의 Map 데이터**</span>가 Object 타입으로  직렬
```suggestion
반면에 <span style="color: #FFA5A5">**MongoDB에서 조회한 Map 데이터**</span>를 비교한 결과는 클라이언트에 전송될 때 데이터가 유지된 채 Object로 직렬화 되고 있었습니다. 이에 따라 <span style="color: #CBF6C1">**gridFS의 Map 데이터**</span>가 Object 타입으로 직렬화 시 데이터가 소실되는 이유와 데이터 소실을 방지하면서 Object 데이터로 직렬화 하기 위한 방법을 찾아야 했습니다.
```

2024-05-21 06:57 UTC, doitchuu commented on README.md
> +- JSON으로 직렬화시 Map을 Object 취급하므로 키-값으로 조회가능한 데이터의 경우 데이터 변환 가능함.
말맺음이 같으면 좋겠어서 아래방식은 어떨까요?

```suggestion
- JSON으로 직렬화시 Map을 Object 취급하므로 키-값으로 조회가능한 데이터의 경우 데이터 변환 가능
```

2024-05-21 10:24 UTC, kyeongjun-ko commented on README.md
> +## 💼 Contents
emoji가 포함되어있는 링크 Id를 수정했습니다.

2024-05-22 10:52 UTC, tjd985 reviewed
확인 했습니다!
이전 리뷰에서 수정사항 반영이 안된 것들이 몇개 보이는데, 그부분만 수정해주시면 될 것 같습니다!

2024-05-22 10:52 UTC, tjd985 commented on README.md
> +    - [6) 문제 해결 : GridFS 파일을 Document 객체와 동일한 Map 구조로 변환](#6-문제-해결--gridfs-파일을-document-객체와-동일한-map-구조로-변환)
소제목을 다 따서 `ToC`를 만들어 주신 점 👍 

링크 작동이 잘 안되는 것들이 있어서 힘드셨을텐데, 고생하셨습니다!!

2024-05-22 10:52 UTC, tjd985 commented on README.md
> +### 1) 문제 원인 : Fabric.js 캔버스의 반복 렌더링
목차만 봐도 어떤 내용일지 알수 있게끔 수정하셨네요 💯

2024-05-23 12:00 UTC, tjd985 submitted a review, later dismissed
확인했습니다!
고생많으셨습니다 👍

2024-05-23 13:01 UTC, doitchuu commented on README.md
> +피그마 디자인 파일의 JSON 데이터를 Fabric.js 객체로 변환하는 맵핑 함수를 구현하였습니다. <br /> 서버에서 전달받은 피그마 데이터를 한번의 순회로 fabric 객체로 모두 변환한 뒤 Canvas에 렌더링 하여서 다양하고 많은 양의 디자인 요소들을 효과적으로 렌더링할 수 있게 되었습니다.
```suggestion
피그마 디자인 파일의 JSON 데이터를 Fabric.js 객체로 변환하는 맵핑 함수를 구현하였습니다. <br /> 
서버에서 전달받은 피그마 데이터를 한 번의 순회로 fabric 객체로 모두 변환한 뒤 Canvas에 렌더링 하여
다양하고 많은 양의 디자인 요소들을 효과적으로 렌더링할 수 있게 되었습니다.
```

2024-05-23 13:03 UTC, doitchuu commented on README.md
> +### 2) 문제 해결 : Fabric.js 캔버스의 sideEffect 처리
목차가 구체적이어진 것 같아 좋네요 👍

2024-05-23 13:04 UTC, doitchuu commented on README.md
> +JSON에 Map 지원이 없는 이유를 직접적으로  명시하지는 않지만 공식문서의 설계 목표와 원칙에서
```suggestion
JSON에 Map 지원이 없는 이유를 직접적으로 명시하지는 않지만 공식문서의 설계 목표와 원칙에서 
```

2024-05-23 13:05 UTC, doitchuu commented on README.md
> +Map을 JSON으로 직렬화 할때 내부 데이터를 유지할 수 있는 방법에 대해서 코드로 확인해 보자면
```suggestion
Map을 JSON으로 직렬화할 때 내부 데이터를 유지할 수 있는 방법에 대해서 코드로 확인해 보자면
```

2024-05-23 13:07 UTC, doitchuu requested changes
경준님 플러그인/서버에 PR하기 전에 띄어쓰기랑 얘기드린 부분 수정 부탁드려요 👍 
고생하셨습니다.

2024-05-23 13:07 UTC, doitchuu commented on README.md
> +`set` 메서드로 추가한 “name” 은 직렬화시 key 값으로 데이터에 접근할수 없으므로 소실되고 object 형태의 key값으로 추가한 “team” 데이터는 key 값으로 데이터에 접근할 수 있으므로 유지됩니다.
```suggestion
`set` 메서드로 추가한 “name” 은 직렬화시 key 값으로 데이터에 접근할 수 없으므로 소실되고 object 형태의 key값으로 추가한 “team” 데이터는 key 값으로 데이터에 접근할 수 있으므로 유지됩니다.
```

2024-05-23 13:07 UTC, doitchuu commented on README.md
> +**`방법 1`** 은 불가능 하다고 판단되어 **`방법 2`** 를 선택했습니다. Map 데이터를 생성시 Object 형태의 키-값 데이터를 함께 저장하면은 Map → Object 직렬화시 내부 데이터를 유지할 수가 있도록 했습니다.
```suggestion
**`방법 1`** 은 불가능 하다고 판단되어 **`방법 2`** 를 선택했습니다. Map 데이터를 생성시 Object 형태의 키-값 데이터를 함께 저장하면 Map → Object 직렬화시 내부 데이터를 유지할 수 있도록 했습니다.
```

2024-05-24 06:47 UTC, doitchuu commented on README.md
> +    - chunk 단위의 데이터 처리를 실패 했을때 null을 `resolve` 메서드에 담아 반환한다.
```suggestion
    - chunk 단위의 데이터 처리를 실패 했을 때 null을 `resolve` 메서드에 담아 반환한다.
```

2024-05-24 06:47 UTC, doitchuu commented on README.md
> +    - gridFS 메서드를 호출한곳에서 gridFS Stream의 반환값이 Falsy 일 때 에러 핸들링을 수행한다.
```suggestion
    - gridFS 메서드를 호출한 곳에서 gridFS Stream의 반환값이 Falsy 일 때 에러 핸들링을 수행한다.
```

2024-05-24 06:57 UTC, doitchuu reviewed
경준님 목차나 리드미 쓰시느라 고생 많으셨습니다. 중간중간 마이너한 수정 필요한 부분이 있어서 요부분이랑 반영 안 된 부분만 같이 반영해주시면 좋을 것 같습니다 👍  고생많으십니다

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +기존 스키마 설계대로 저장된 <span style="color: #CBF6C1">document 객체의 Map 타입</span>과 <span style="color: #FFA5A5">gridFS 파일 데이터의 Object 타입</span>을 같게 하기 위해서 <i><u>gridFS 데이터를 반환하기 전 Map 자료구조로 변환하는 로직을 수행</u></i>
```suggestion
기존 스키마 설계대로 저장된 <span style="color: #CBF6C1">document 객체의 Map 타입</span>과 <span style="color: #FFA5A5">gridFS 파일 데이터의 Object 타입</span>을 같게 하기 위해서 <i><u>gridFS 데이터를 반환하기 전 Map 자료구조로 변환하는 로직을 수행</u></i>하도록 하여서 문제를 해결할 수 있었습니다.
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +  즉, 사용자의 mouseHover 이벤트가 발생에 따라 동적으로 <span style="color: #FFA5A5">**변경된 내용의 텍스트 객체**</span>가 보여지도록 display 속성 값이 바뀌도록 하고자 했습니다. <br />
하고자를 지우거나 바뀌게 만들었다라는 식으로 말해도 좋을 것 같습니다 👍 

```suggestion
  즉, 사용자의 mouseHover 이벤트가 발생에 따라 동적으로 <span style="color: #FFA5A5">**변경된 내용의 텍스트 객체**</span>가 보여지도록 display 속성 값이 바뀌도록 했습니다. <br />
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +서버에서 <span style="color: #CBF6C1">**gridFS의 Map 데이터**</span>를 비교한 결과를 클라이언트에 전송하기 위해서 Map 구조가 Object로 직렬화 될때 Map 내부 데이터가 소실되어 빈 객체를 전달하고 있었습니다.
```suggestion
서버에서 <span style="color: #CBF6C1">**gridFS의 Map 데이터**</span>를 비교한 결과를 클라이언트에 전송하기 위해서 Map 구조가 Object로 직렬화될 때 Map 내부 데이터가 소실되어 빈 객체를 전달하고 있었습니다.
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +반면에 <span style="color: #FFA5A5">**MongoDB에서 조회한 Map 데이터**</span>를 비교한 결과는 클라이언트에 전송하기 위해서 Map 구조가 Object로 직렬화 될때 Map 내부 데이터를 유지하면서 Object로 변환되어 결과를 전달하고 있었습니다.
```suggestion
반면에 <span style="color: #FFA5A5">**MongoDB에서 조회한 Map 데이터**</span>를 비교한 결과는 클라이언트에 전송하기 위해서 Map 구조가 Object로 직렬화될 때 Map 내부 데이터를 유지하면서 Object로 변환되어 결과를 전달하고 있었습니다.
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +Map 데이터가 Object 로 변환되면서 Map 내부 데이터가 소실되고 빈 객체  `{}` 를 반환하고 있어서  프레임 내부 노드 데이터인 “nodes” 가 소실되고 캔버스에 렌더링 될때 빈 프레임만 렌더링 되는 에러가 발생했습니다.
해당 부분도 변환되면서 -> 반환하고 있어서 -> 소실되고로 문장이 계속 이어져서 분리해서 써도 좋을 것 같습니다.

```suggestion
Map 데이터가 Object 로 변환되면서 Map 내부 데이터가 소실되고 빈 객체  `{}` 를 반환하고 있었습니다. 또한(혹은 다른 문제로는 등) 프레임 내부 노드 데이터인 “nodes” 가 소실되고 캔버스에 렌더링 될 때 빈 프레임만 렌더링 되는 에러가 발생했습니다.
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +서버에서 데이터를 전송할때 연속된 형태의 JSON 형식으로 변환하는 직렬화 과정을 거치는데 이때 Map 내부 데이터가 소실되는이유는 `JSON`에는 Map을 처리할 수 없어서 Map을 일반 Object 객체로 취급하게 되기 때문에 Map 에서 Object 형태 (키-값) 로 접근할 수 있는 데이터가 없는 경우 빈 객체 `{}` 를 반환합니다.
```suggestion
서버에서 데이터를 전송할 때 연속된 형태의 JSON 형식으로 변환하는 직렬화 과정을 거치는데 이때 Map 내부 데이터가 소실되는이유는 `JSON`에는 Map을 처리할 수 없어서 Map을 일반 Object 객체로 취급하게 되기 때문에 Map 에서 Object 형태 (키-값) 로 접근할 수 있는 데이터가 없는 경우 빈 객체 `{}` 를 반환합니다.
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +그렇다면 왜 <span style="color: #FFA5A5">MongoDB에서 조회한 Map 데이터</span>는 Object 직렬화시 왜 Map 내부 데이터가 소실되지 않을까?
```suggestion
그렇다면 왜 <span style="color: #FFA5A5">MongoDB에서 조회한 Map 데이터</span>는 Object 직렬화 시 왜 Map 내부 데이터가 소실되지 않을까?
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +> **즉, Object 형태의 키-값으로 접근할 수 있는 데이터의 경우 JSON으로 직렬화시 데이터가 유지됩니다.**
```suggestion
> **즉, Object 형태의 키-값으로 접근할 수 있는 데이터의 경우 JSON으로 직렬화 시 데이터가 유지됩니다.**
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +> **❌ 방법 1.**  gridFS 파일 Map 변환시 Javascript Map 이 아닌 BSON Map 으로 변환하기 ( 불가능 )
```suggestion
> **❌ 방법 1.**  gridFS 파일 Map 변환 시 Javascript Map 이 아닌 BSON Map 으로 변환하기 ( 불가능 )
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +> **✅  방법2.**  gridFS 파일 Map 변환시 Object 형태의 데이터 (키- 값) 추가 해추기
```suggestion
> **✅  방법2.**  gridFS 파일 Map 변환 시 Object 형태의 데이터 (키- 값) 추가 해추기
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +- JSON으로 직렬화시 Map을 Object 취급하므로 키-값으로 조회가능한 데이터의 경우 데이터 변환 가능
```suggestion
- JSON으로 직렬화 시 Map을 Object 취급하므로 키-값으로 조회가능한 데이터의 경우 데이터 변환 가능
```

2024-05-24 06:57 UTC, doitchuu commented on README.md
> +**`방법 1`** 은 불가능 하다고 판단되어 **`방법 2`** 를 선택했습니다. Map 데이터를 생성시 Object 형태의 키-값 데이터를 함께 저장하면 Map → Object 직렬화시 내부 데이터를 유지할 수 있도록 했습니다.
```suggestion
**`방법 1`** 은 불가능하다고 판단되어 **`방법 2`** 를 선택했습니다. Map 데이터를 생성 시 Object 형태의 키-값 데이터를 함께 저장하면 Map → Object 직렬화 시 내부 데이터를 유지할 수 있도록 했습니다.
```

2024-05-24 07:16 UTC, tjd985 reviewed
`P3` 코멘트 남겨두었습니다!
확인 부탁드려요!

2024-05-24 07:16 UTC, tjd985 commented on README.md
> +2. 데이터 크기에 따라 다른 방식으로 저장 : 데이터의 크기가 상수화 해놓은 16MB 이상인지 이하인지 여부에 따라서 <span style="color: #CBF6C1">gridFS 파일 형태로 저장할지 </span>스키마 구조대로 컬렉션에 <span style="color: #FFA5A5">Document 로 저장할지 </span> 분기처리 하였습니다
- `P3`
```suggestion
1. **데이터의 크기 구하기**
MongoDB에 저장하려는 피그마 데이터는 Javascript Object 타입으로 파일의 크기를 구하기 위해 연속적인 데이터 형태로 JSON으로 직렬화 하기 위해서 `JSON.stringify`를 사용하고 `length`를 사용해서 문자열의 길이로 대략적인 파일의 크기를 구했습니다.

2. **데이터 크기에 따라 다른 방식으로 저장**
데이터의 크기가 상수화 해놓은 16MB 이상인지 이하인지 여부에 따라서 <span style="color: #CBF6C1">gridFS 파일 형태로 저장할지 </span>스키마 구조대로 컬렉션에 <span style="color: #FFA5A5">Document 로 저장할지 </span> 분기처리 하였습니다.
```

이런식으로 `제목`과 `설명`을 줄바꿈해서 처리한다면 더욱 가독성이 좋을 것 같습니다!

2024-05-24 07:16 UTC, tjd985 commented on README.md
> +피그마 파일 데이터가 `16MB 이하인 경우`, 설계된 <span style="color: #CBF6C1">스키마에 따라 Map 형식으로 문서가 저장</span>됩니다. 반면, <span style="color: #FFA5A5">GridFS 파일은 피그마 파일 데이터 Object 타입 그대로 저장</span>되므로, Map 구조를 기반으로 동작하는 `비교
- `P3`
```suggestion
피그마 파일 데이터가 `16MB 이하인 경우`, 설계된 <span style="color: #CBF6C1">스키마에 따라 Map 형식으로 문서가 저장</span>됩니다. <br />
반면, <span style="color: #FFA5A5">GridFS 파일은 피그마 파일 데이터 Object 타입 그대로 저장</span>되므로, Map 구조를 기반으로 동작하는 `비교 로직 수행 시 에러가 발생`했습니다.
```

줄이 길어서 가독성을 조금 해치는 것 같아요.
줄바꿈 해주는 건 어떨까요?

2024-05-24 09:40 UTC, doitchuu commented on README.md
> +    - 각 청크는 독립적으로 전송되므로 네트워크 대역폭을 효율적으로 활용하고 전송시간을 단축 합니다.
```suggestion
    - 각 청크는 독립적으로 전송되므로 네트워크 대역폭을 효율적으로 활용하고 전송시간을 단축합니다.
```

2024-05-25 12:07 UTC, tjd985 approved these changes
확인했습니다!
고생하셨습니다!! 💯

2024-05-26 14:10 UTC, doitchuu approved these changes
코멘트 반영하시느라 고생많으셨습니다 👍

2024-05-27 01:56 UTC, merged